### GENERAL ####
samples_file: config/samples.csv
result_dir: /path/to/results/directory
data_dir: /path/to/input/data/directory

sample_layouts: PE # PE for paired-end or SE for single-end layout
fqext1: 1 # E.g for a file named "SRR583892_1.fastq" the fqext1 is 1
fqext2: 2 # E.g for a file named "SRR583892_2.fastq" the fqext2 is 2
fqsuffix: fastq # E.g for a file named "SRR583892_1.fastq" the fqsuffix is fastq


### DATA ACQUISITION MODULE ### Input: sample_id from samples_file
getdata: true  # Flag to perform the Data Acquisition step using SRA-tools or not. This step will download the samples from SRA in the data_dir

getdata_options: " " # Optional parameters for SRA-tools (v2.10.1) (e.g. -X 50000 to download only the first 50k reads per sample), for available options please visit the SRA-tools documentation


### PRE-PROCESS MODULE ### Expected Input-SE: {data_dir}/{sample_id}.{fqsuffix}.gz | Input-PE: {data_dir}/{sample_id}_{fqext1}.{fqsuffix}.gz , {data_dir}/{sample_id}_{fqext2}.{fqsuffix}.gz   (sample_id from samples_file)
preprocess: true # Flag to perform the Pre-process step or not.

trim_options: "--quality 10 --length 20 --consider_already_trimmed 10" # optional parameters for TrimGalore (v0.6.6), for available options please visit the TrimGalore documentation
# For specific adapter removal, add the -a flag in the options above eg.: -a TCGATTGAACGGT 


### ALIGNMENT MODULE ### Expected Input-SE: {data_dir}/{sample_id}.{fqsuffix}.gz | Expected Input-PE: {data_dir}/{sample_id}_{fqext1}.{fqsuffix}.gz , {data_dir}/{sample_id}_{fqext2}.{fqsuffix}.gz   (sample_id from samples_file)
alignment: true # Flag to perform the Alignment step or not.

aligner: star # Available options= [star]
alignment_index_dir: /path/to/star/index/directory
genome_assembly: GRCh38 # The name of the assembly used e.g. "GRCh38". This will be used in naming for distinction puproses on the result files
annotation_file: /path/to/annotation/file # Uncompressed (.gtf/.gff3) Please provide a .gtf wherever possible. Tested with Gencode, Ensembl and RefSeq annotations.
align_params: " " # Aligner specific parameter options, please refer to the aligner documentation for available options

# Parameters for index generation. If an index is not found in the alignment_index_dir, an "/{genome_assembly}-{aligner}_index" subdirectory will be created and these will be used to generate one using the provided aligner
genome_fasta: /path/to/genome/fasta/file.fa
genome_sizes_file: /path/to/genome/sizes/file.fa.fai # Provide the .sizes or .fai genome file containing chromosome/contig sizes 
genome_index_params: "--limitGenomeGenerateRAM 50000000000 --genomeSAsparseD 1" # Aligner specific parameter options for alignment index generation, please refer to the aligner documentation for available options


### QUANTIFICATION MODULE ### Expected Input: {data_dir}/{sample_id}.bam  (sample_id from samples_file, for RSEM please provide an appropriate aligned-to-transcriptome .bam file)
quantification: true # Flag to perform the Quantification step or not.

quantifier: featurecounts # Available options= [featurecounts, rsem, star, salmon]  (the "star" option is only available in conjunction with the execution of the alignment module using the aligner "star", moreover the quant_params are not used with this option)
quant_params: " " # Quantifier specific parameter options, please refer to the quantifier documentation for available options
quant_index: /path/to/quantifier/index/directory # (ONLY used by quantifiers RSEM and Salmon) Quantification index directory, RSEM also requires the index prefix in this parameter (e.g. /path/to/quantifier/index/directory/prefix). If the quantifier requires one and index and it is not detected here, it will be created using annotation_file and genome_fasta. If provided, it must have been created using the exact same genome and annotation files used for the alignment index to avoid biased/incorrect results.


### QUALITY CONTROL MODULE ### Expected Input: {data_dir}/{sample_id}.bam  (sample_id from samples_file, please provide a sorted aligned-to-genome .bam file)
afterqc: true # Flag to perform the After QC step or not.

junction_analysis: true # Perform Junction-Annotation and -Saturation analysis using RSeQC (v3.0.1), please refer to RSeQC's documentation for more information
annotation_bed_file: /path/to/bed-12/annotation/file.bed # A 12-column BED file from the exact annotation used in the samples' upstream analysis. If quantification module is executed a .bed file is automatically generated from the annotation file given, otherwise please provide an annotation .bed file for the QC analysis (ucsc-gtftogenepred/ucsc-gff3togenpred + ucsc-genepredtobed are proposed for a GTF/GFF3 conversion to a proper 12-column bed file) (required for Read_distribution, Inner_distance and Junction analyses)


